### ISSUE TITLE
Mysterious EtherLynx

### ISSUE THREAD

**Issue by bentayloruk** [mTorp22/EtherLynx#1]
The repository description for this repo is "Communication tool for Danfoss TLX / FLX inverters over ethernet".  I've seen EtherLynx mentioned in an SMA web page too.  The text I have seen says the following:

"By implementing EtherLynx and protocol it is now possible to connect Danfoss TLX and FLX inverters to the SMA Data Manager M via Ethernet wiring."

This repo is empty and I can't find much of anything on EtherLynx in relation to Danfoss TLF inverters.  Do you have any information on the protocol or an implementation you can share?  Please let me know.

**Comment by mTorp22** [comment]
Hi Sorry for the late answer, I just uploaded another project, which also holds the description of the Etherlynx protocol used for TLX, FLX... have a look at https://github.com/mTorp22/LynxCmd.git   
I use this on a Raspberry Pi to talk to my TLX

**Comment by bentayloruk** [comment]
No worries at all, thanks for answering! It's really cool that you have the spec description.

I just had a look at the LynxCmd repos, but it is empty for me. Am I missing something?
<img width="825" alt="image" src="https://user-images.githubusercontent.com/189409/174479964-0993f238-fe80-465f-9cb8-ce9fdca9d448.png">

**Comment by mTorp22** [comment]
Hi I was missing something... not used to git.... is now published

**Comment by bentayloruk** [comment]
Git takes some getting used to :)

Thanks so much for persisting and publishing your code. I'm overly excited about trying this out! I mainly program in F# and C# so this is perfect.
